name: üåê Build Developer Site

on:
  pull_request:
  push:
    paths:
      - 'spec/marketing.json'
      - 'spec/transactional.json'
    branches:
      - master

env:
  REBUILD_PROD: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }} # true iff push to master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: POST Prod Build Hook
        run: curl -X POST -d {} ${{ env.NETLIFY_PROD_BUILD_HOOK }}
        if: env.REBUILD_PROD == 'true'
        env:
          NETLIFY_PROD_BUILD_HOOK: ${{ secrets.NETLIFY_PROD_BUILD_HOOK }}
      - name: POST Staging Build Hook
        run: curl -X POST -d {} ${{ env.NETLIFY_STAGING_BUILD_HOOK }}
        if: env.REBUILD_PROD != 'true'
        env:
          NETLIFY_STAGING_BUILD_HOOK: ${{ secrets.NETLIFY_STAGING_BUILD_HOOK }}
      - name: POST Dev Build Hook
        run: curl -X POST -d {} ${{ env.NETLIFY_DEV_BUILD_HOOK }}
        if: env.REBUILD_PROD == 'true'
        env:
          NETLIFY_DEV_BUILD_HOOK: ${{ secrets.NETLIFY_DEV_BUILD_HOOK }}
